# Generated by Django 2.1.7 on 2019-02-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190222_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.TextField(default='Descripción del producto', max_length=500),
        ),
    ]
