# Generated by Django 3.0.5 on 2020-04-12 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Rut', models.IntegerField(default=0)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Operador', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(default=False)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Estado', models.BooleanField(default=False)),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedido')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
