# Generated by Django 3.0.5 on 2020-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ingresoproducto_pedido_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
