# Generated by Django 2.1.7 on 2019-02-22 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=1)),
                ('TotalDetalle', models.IntegerField(default=0)),
                ('Estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(blank=True, default=datetime.date(2019, 2, 22))),
                ('Hora', models.TimeField(blank=True, default=datetime.time(1, 30, 36, 148527))),
                ('Vendedor', models.CharField(max_length=50)),
                ('TotalAPagar', models.IntegerField(default=0)),
                ('Estado', models.BooleanField(default=False)),
                ('TipoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.TipoPago')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='NumeroVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
