# Generated by Django 2.1.7 on 2019-02-22 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190222_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopago',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.time(21, 44, 4, 209467)),
        ),
    ]
