# Generated by Django 3.0.5 on 2020-04-12 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20190222_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.time(18, 29, 31, 667360)),
        ),
    ]
