# Generated by Django 3.0.5 on 2020-04-12 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20200412_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.time(20, 33, 55, 825561)),
        ),
    ]
