# Generated by Django 3.0.5 on 2020-04-14 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20200412_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 14)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.time(22, 39, 54, 734979)),
        ),
    ]
